version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "daily"
    allowed_updates:
      - match:
          update_type: "security"
  - package-ecosystem: "npm"
    directory: "/server"
    schedule:
      interval: "daily"
    allowed_updates:
      - match:
          update_type: "security"
