name: Docker

on:
  push:
    branches:
      - main

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build image
        run: docker build -t romitou/eventsstats:latest .
        working-directory: ./server

      - name: Log in to registry
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u romitou --password-stdin

      - name: Push image
        run: docker push romitou/eventsstats:latest
