name: ESLint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node 16
      uses: actions/setup-node@v2
      with:
        node-version: 16
    - name: Install dependencies
      working-directory: ./client
      run: yarn
    - name: Run lint
      working-directory: ./client
      run: yarn lint
